app:
  name: "Web Log Analyzer"
  version: "1.0.0"
  log_dir: "/var/log/web_log_analyzer"
  max_log_size: "10MB"
  keep_logs: 7

analysis:
  daily_schedule: "00:00"
  retention_days: 30
  anomaly_threshold: 3.0

ui:
  refresh_interval: 5000
  theme: "light"